version: "3.3"

services:
  documents-storage-api:
    container_name: documents-storage-api
    restart: always
    image: tafeen/documents-storage-api:v0.9.0
    hostname: documents-storage-api
    environment:
      - HOST_IP="localhost"
    ports:
      - 8080:8000
    volumes:
      - documents_storage_data:/usr/src/app/documents-storage-api
    networks:
      - documents_storage_fe
      - documents_storage_be

  documents-storage-ui:
    container_name: documents-storage-ui
    restart: always
    image: tafeen/documents-storage-ui:v0.9.0
    environment:
      - API_URL="http://localhost:8080"
    build: ../documents-storage-ui
    ports:
      - 5000:5000
    networks:
      - documents_storage_fe

  documents-storage-db:
    container_name: documents-storage-db
    hostname: documents-storage-db
    restart: always
    image: mongo:5.0.5
    volumes:
      - documents_storage_db:/data/db
    networks:
      - documents_storage_be

networks:
  documents_storage_fe:
  documents_storage_be:

volumes:
  documents_storage_data:
  documents_storage_db: