name: Code Test Coverage and Security
on: push
jobs:
  codecov:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: ‘2’

    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7

    - name: Setup MongoDB
      uses: supercharge/mongodb-github-action@1.7.0

    - name: Generate Report
      run: |
        pip install -r ./requirements.txt
        pip install coverage
        pip install pytest
        export PYTHONPATH=documents_storage_api
        printf "PYTHONPATH=documents_storage_api \n \
        DEBUG=True \n \
        TEST=True \n \
        DB_URL=mongodb://127.0.0.1:27017/documents-storage \n \
        HOST_IP=127.0.0.1 \n \
        API_HOST=127.0.0.1 \n \
        API_PORT=8000 \n \
        API_ORIGINS=['http://localhost:5000', 'http://localhost:8000'] \n \
        API_JWT_SECRET='test_secret'" > .env
        coverage run --source routers -m pytest
        coverage xml
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: coverage.xml
        fail_ci_if_error: true
        verbose: true
  code_security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for python vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.code.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.code.sarif
  config_security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Mkdir results-dir
        run: mkdir -p results-dir
      - name: Run KICS Scan with SARIF result
        uses: checkmarx/kics-github-action@v1.5
        with:
          path: './'
          exclude_queries: 451d79dc-0588-476a-ad03-3c7f0320abb3
          ignore_on_exit: results
          fail_on: high
          output_path: results-dir
          output_formats: 'sarif'
      - name: Show results
        run: |
          cat results-dir/results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results-dir/results.sarif